### ISSUE TITLE
Bug in data blood type

### ISSUE THREAD

**Issue by riskykurniawan15** [SquadSumatera/flutter_donor#59]
![IMG_20220109_111128](https://user-images.githubusercontent.com/62739625/148669137-b09e9087-3be6-43b1-8fee-0ed09280ff10.jpg)
Sepertinya saya menemukan bug pada tipe darah di bagian profile. Disana menunjukan tanda "-" bukan data golongan darah

**Comment by dikynugraha1111** [comment]
Close #59 
Fix : Done. Update on publish app v.4
